version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "products"
    ports:
    - 5432:5432
  web-app:
    container_name: web_app
    image: blinel/web_app
    ports:
    - 5000:5000