version: "3"
services:
  web:
    container_name: web
    build:
      context: "."
      dockerfile: "docker/Dockerfile.web"
    ports:
      - 5000:5000
    depends_on:
      - database
  database:
    container_name: database
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "products"
    build:
      context: "."
      dockerfile: "docker/Dockerfile.database"
    ports:
    - 5432:5432